# Generated by Django 3.1.2 on 2020-11-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_pelicula_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='descripcion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
