# Generated by Django 3.1.2 on 2020-11-30 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_pelicula_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('destacado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='pelicula',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pelis'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='precio',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.genero'),
        ),
    ]
