# Generated by Django 3.1.2 on 2020-11-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20201130_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='nombre',
        ),
        migrations.AddField(
            model_name='genero',
            name='tipo_genero',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
