# Generated by Django 3.1.2 on 2020-11-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_auto_20201130_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='tipo_genero',
            field=models.CharField(max_length=100),
        ),
    ]
