# Generated by Django 3.1.2 on 2020-11-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_20201130_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='url',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
