# Generated by Django 2.2.7 on 2020-12-15 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_pelicula_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='url',
        ),
    ]
