# Generated by Django 3.1.4 on 2020-12-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_remove_pelicula_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='director',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='trailer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
